# Generated by Django 4.2.1 on 2023-05-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0002_question_description_question_number_of_questions_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="description",
        ),
        migrations.AddField(
            model_name="quizsubject",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
